/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

package edu.progAvUD.taller2.vista;

/**
 *
 * @author Andres Felipe
 */
public class PanelCarta extends javax.swing.JPanel {

    /** Creates new form panelCarta */
    public PanelCarta() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelDenominacionCarta1 = new javax.swing.JLabel();
        jLabelDenominacionCarta2 = new javax.swing.JLabel();
        jLabelFiguraCarta = new javax.swing.JLabel();

        setBackground(new java.awt.Color(207, 207, 207));

        jLabelDenominacionCarta1.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabelDenominacionCarta1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelDenominacionCarta1.setText("10");

        jLabelDenominacionCarta2.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabelDenominacionCarta2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelDenominacionCarta2.setText("10");

        jLabelFiguraCarta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelFiguraCarta.setPreferredSize(new java.awt.Dimension(50, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelFiguraCarta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelDenominacionCarta2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelDenominacionCarta1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabelDenominacionCarta1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabelFiguraCarta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabelDenominacionCarta2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel jLabelDenominacionCarta1;
    public javax.swing.JLabel jLabelDenominacionCarta2;
    public javax.swing.JLabel jLabelFiguraCarta;
    // End of variables declaration//GEN-END:variables

}
