/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu.progAvUD.taller2.vista;

import edu.progAvUD.taller2.control.ControlGrafico;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Andres Felipe
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    private ControlGrafico controlGrafico;
    public PanelPrincipal panelPrincipal;
    public PanelMesa panelMesa;
    public DialogComprarFichas dialogComprarFichas;

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal(ControlGrafico controlGrafico) {
        this.controlGrafico = controlGrafico;
        initComponents();
        setVisible(true);
        this.panelPrincipal = new PanelPrincipal();
        this.panelMesa = new PanelMesa();
        this.dialogComprarFichas = new DialogComprarFichas(this, true);
    }

    public File pedirArchivoSerializacion() {
        JFileChooser fileChooser = new JFileChooser(System.getProperty("user.dir") + "/src/main/java/edu/progAvUD/taller2/data");
        fileChooser.setFileFilter(new FileNameExtensionFilter("Archivos .bin", "bin"));
        fileChooser.showOpenDialog(null);
        return fileChooser.getSelectedFile();
    }

    public File pedirArchivoAleatorio() {
        JFileChooser fileChooser = new JFileChooser(System.getProperty("user.dir") + "/src/main/java/edu/progAvUD/taller2/data");
        fileChooser.setFileFilter(new FileNameExtensionFilter("Archivos .dat", "dat"));
        fileChooser.showOpenDialog(null);
        return null;
    }

    /**
     * Muestra un cuadro de diálogo con un mensaje de éxito.
     *
     * @param mensaje Mensaje a mostrar al usuario.
     */
    public void mostrarMensajeExito(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje, "Éxito", JOptionPane.INFORMATION_MESSAGE);
    }

    /**
     * Muestra un cuadro de diálogo con un mensaje de error.
     *
     * @param mensaje Mensaje a mostrar al usuario.
     */
    public void mostrarMensajeError(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje, "Error", JOptionPane.ERROR_MESSAGE);
    }

    public File pedirArchivo() {
        JFileChooser fileChooser = new JFileChooser(System.getProperty("user.dir") + "/src/main/java/edu/progAvUD/taller2/data");

        // Aplica un filtro para archivos .properties
        fileChooser.setFileFilter(new FileNameExtensionFilter("Archivos .properties", "properties"));
        fileChooser.showOpenDialog(null);
        // Mostrar el diálogo
        return fileChooser.getSelectedFile();
    }

    public void mostrarPanel(JPanel panel) {
        setContentPane(panel);
        pack(); // Ajusta el tamaño de la ventana según el contenido
        setLocationRelativeTo(null); // Centra la ventana en la pantalla
        revalidate();
        repaint();
    }

    public PanelCarta crearCarta(String numeroCarta, String palo) {
        PanelCarta carta = new PanelCarta();
        String path = System.getProperty("user.dir") + "/src/main/java/edu/progAvUD/taller2/imagenes/" + palo + ".png";
        ImageIcon imagenCarta = new ImageIcon(path);
        carta.jLabelFiguraCarta.setIcon(imagenCarta);
        carta.jLabelDenominacionCarta1.setText(numeroCarta);
        carta.jLabelDenominacionCarta2.setText(numeroCarta);
        return carta;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
